services:
  - type: web
    name: app_web
    runtime: python
    repo: https://github.com/Ferstrom/aplicacion_web.git
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py 8081
    rootDir: ./web

  - type: web
    name: api_rest
    runtime: python
    repo: https://github.com/Ferstrom/api_rest.git
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run app.py
    rootDir: ./app
