services:
  - type: web
    name: app_web
    runtime: python
    repo: https://github.com/Ferstrom/aplicacion_web.git
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py 8081
    rootDir: ./web

  - type: web
    name: api_rest
    runtime: python
    repo: https://github.com/Ferstrom/api_rest.git
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: fastapi run main.py
    rootDir: ./app

# Exported from Render on 2024-10-25T21:09:16Z
databases:
- name: agenda
  databaseName: db_agenda_u1pv
  user: user
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
